apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: ruchitadarur/student-survey:v1  # ✅ Use versioned image
        imagePullPolicy: Always  # ✅ Ensures Kubernetes fetches the latest image
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  selector:
    app: student-survey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # ✅ Corrected placement of nodePort
  type: NodePort  # ✅ Use NodePort for local testing

