apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app
  labels:
    app: survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app
          image: ${DOCKER_USERNAME}/survey-app:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
