apiVersion: v1
kind: Service
metadata:
  name: survey-app-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: survey-app
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 35.202.41.70
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
